channels:
  - pythonocc
  - oce
  - dlr-sc
  - conda-forge
  - tpaviot
  - skoch9
  - pytorch
dependencies:
  - numpy
  - scipy
  - meshplot
  - igl
  - wildmeshing
  - polyfempy
  - cadmesh
  - pytorch-cpu
  - torchvision-cpu
  - pip
  - pip:
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - torch-geometric
